version: '3.3'

services:
    web:
        image: dongdaohieu/is_rest:latest
        networks:
          - web
    frontend:
        image: dongdaohieu/angular_ui_docker:latest
        ports:
          - "80:80"
        networks:
          - frontend
          - web

networks:
  web:
  frontend: